# Generated by Django 5.2.6 on 2025-10-09 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='date',
            new_name='available_date',
        ),
    ]
